declare -A modules=(
    ["Secure Boot"]="secure_boot 4"
    ["Update Preload Keys"]="update_preloaded_keys 2"
    ["Bootloader Password"]="bootloader_password 2"
    ["Protecting Kernel's Cmdline & Initramfs"]="protect_kernel_cmdline_initramfs 4"
    ["Enabled IOMMU"]="enabled_IOMMU 3"
    ["Configuring the memory options"]="memory_options 2"
    ["Kernel configuration options"]="kernel_config_opts 2"
    ["Disabling kernel modules loading"]="disable_kernel_modules 3"
    ["Yama security module"]="yama_ptrace 2"
    ["IPV4 Configuration"]="ipv4_config 2"
    ["Disabling IPv6"]="disabling_ipv6 2"
    ["File System Configuration"]="fs_config 2"
    ["Memory kernel Compile Options"]="memory_kernel_compile_opts 4"
    ["Data structures kernel Compile Options"]="ds_kernel_compile_opts 4"
    ["Memory allocator kernel Compile Options"]="ma_kernel_compile_opts 4"
    ["Managment of Kernel Modules Options"]="mkm_kernel_opts 4"
    ["Abnormal error handling kernel Compile Options"]="aeh_kernel_compile_opts 4"
    ["Security functions kernel Compile Options"]="sf_kernel_compile_opts 4"
    ["Plugins Kernel Compile Options"]="pg_kernel_compile_opts 4"
    ["IP stack kernel Compile Options"]="ip_kernel_compile_opts 4"
    ["Kernel Behaviors Compile Options"]="kb_kernel_compile_opts 4"
    ["Hardware Architecture dependent Configuration"]="archi_dep_compile_opts 4"
    ["Typical partitioning scheme"]="typical_partitioning_scheme 2"
    ["Access restrictions on /boot"]="restrict_boot_mounting 3"
    ["Removing the unused user accounts"]="rm_unused_accounts 1"
    ["Configuring a timeout on local user sessions"]="timeout_local_user_sessions 2"
    ["Disabling the service accounts"]="disable_service_accounts 2"
    ["Changing the default value of UMASK"]="umask_value 3"
    ["Using Mandatory Access Control features"]="m_access_control 3"
    ["Create a group dedicated to the use of sudo"]="sudo_group 3"
    ["Sudo Configuration Guidelines"]="sudo_config 2"


)